### ISSUE TITLE
I got always CUDA error: out of memory in my RTX 5090!!!

### ISSUE THREAD

**Issue by merecesarchviz** [numz/ComfyUI-SeedVR2_VideoUpscaler#181]
I try all and i always got Cuda error!! in my Rtx 5090 32GVram, I swap the models 5b and also try 3b, i decrease the video frames count! but always pop up the cuda out of memory error, any idea what is happening?

<img width="2018" height="1131" alt="Image" src="https://github.com/user-attachments/assets/4e6f4a1f-2e84-409f-aa55-198e775d4fa1" />

<img width="1794" height="1054" alt="Image" src="https://github.com/user-attachments/assets/cea950ea-f10a-4483-aebb-1da308877fb2" />

**Comment by merecesarchviz** [comment]
> Hi [@merecesarchviz](https://github.com/merecesarchviz)
> 
> install new nightly version and change workflow.
> 
> cd C:\ComfyUI\ComfyUI\custom_nodes del C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SeedVR2_VideoUpscaler
> 
> git clone -b nightly https://github.com/NumZ/ComfyUI-SeedVR2_VideoUpscaler.git
> 
> cd C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SeedVR2_VideoUpscaler python.exe -m pip install -r requirements.txt

That solved it! now all works perfect, thank you for the help!
