### ISSUE TITLE
[Bug] Multi RTX 4090 GPU run hits CUDA OOM

### ISSUE THREAD

**Issue by llag9810** [numz/ComfyUI-SeedVR2_VideoUpscaler#30]
## Describe the bug

Running the `inference_cli.py` on a server with multiple RTX 4090 GPUs (e.g. `--cuda_device 0,1,2,3,4,5,6,7`) results in the last few workers processes crashing with **CUDA out-of-memory (OOM)** errors, although the same video finishes successfully on a single GPU.

All cards are RTX 4090 (24 GB), and the 3B FP16 model successfully fits on one card in single-GPU mode.

## Reproduction
```
python inference_cli.py --video_path <MY_INPUT_VIDEO> --batch_size 1 --model seedvr2_ema_3b_fp8_e4m3fn.safetensors --resolution 1080  --output <MY_OUTPUT_PATH> --cuda_device 0,1,2,3,4,5,6,7 --preserve_vram --debug
```

Worker 0 start inference, but other workers crash almost immediately with OOM.

## Environment
Ubuntu 22.04, 8*RTX 4090 (24 GB each), CUDA 12.4

## Probable root cause
* The script sets spawn as the multiprocessing start-method:
  ```
  mp.set_start_method('spawn', force=True)
  ```

* With spawn, each child interpreter **re-executes the entire script**. Heavy CUDA imports like "`import torch, torch.cuda.init()`", etc. live at module scope, so they execute before `_worker_process` set `CUDA_VISIBLE_DEVICES`.

* Torch initializes on each process, while it still “sees” all GPUs and latches onto physical GPU 0. Later, inside _worker_process:
  ```
  os.environ["CUDA_VISIBLE_DEVICES"] = str(device_id)  # too late
  ```
  has no effect on the already-initialized Torch context — every worker allocates on GPU 0, leading to OOM.

---
Happy to open a PR with the fix if desired. Thanks for the project!

**Comment by Luchuanzhao** [comment]
Hi~
 I also encountered the same problem. My idea is to pass the device_id to every function that moves the models to gpu, but there are too much code involved, and it is very inefficient. Do you have any ideas for fixing it?

**Comment by Luchuanzhao** [comment]
> ## Describe the bug
> Running the `inference_cli.py` on a server with multiple RTX 4090 GPUs (e.g. `--cuda_device 0,1,2,3,4,5,6,7`) results in the last few workers processes crashing with **CUDA out-of-memory (OOM)** errors, although the same video finishes successfully on a single GPU.
> 
> All cards are RTX 4090 (24 GB), and the 3B FP16 model successfully fits on one card in single-GPU mode.
> 
> ## Reproduction
> ```
> python inference_cli.py --video_path <MY_INPUT_VIDEO> --batch_size 1 --model seedvr2_ema_3b_fp8_e4m3fn.safetensors --resolution 1080  --output <MY_OUTPUT_PATH> --cuda_device 0,1,2,3,4,5,6,7 --preserve_vram --debug
> ```
> 
> Worker 0 start inference, but other workers crash almost immediately with OOM.
> 
> ## Environment
> Ubuntu 22.04, 8*RTX 4090 (24 GB each), CUDA 12.4
> 
> ## Probable root cause
> * The script sets spawn as the multiprocessing start-method:
>   ```
>   mp.set_start_method('spawn', force=True)
>   ```
> * With spawn, each child interpreter **re-executes the entire script**. Heavy CUDA imports like "`import torch, torch.cuda.init()`", etc. live at module scope, so they execute before `_worker_process` set `CUDA_VISIBLE_DEVICES`.
> * Torch initializes on each process, while it still “sees” all GPUs and latches onto physical GPU 0. Later, inside _worker_process:
>   ```
>   os.environ["CUDA_VISIBLE_DEVICES"] = str(device_id)  # too late
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   has no effect on the already-initialized Torch context — every worker allocates on GPU 0, leading to OOM.
> 
> Happy to open a PR with the fix if desired. Thanks for the project!

Thanks for your analysis, I have solved it by delaying CUDA initialization~

**Comment by WKCrypt0** [comment]
Does this apply to the ComfyUI node?
I am getting the error “All tensors were expected to be on the same device, but at least two devices were found, cuda:1 and cuda:0. (when checking the argument for argument mat1 in method wrapper_CUDA_addmm).”
I have 2x3090Ti
If you want to modify the code and have me test it, I'm happy to do so. I would love to be able to use this great upscaler!
Thanks!
