### ISSUE TITLE
[Question] OOM Error and Incorrect Process Distribution During Multi-GPU Inference

### ISSUE THREAD

**Issue by nkkbr** [numz/ComfyUI-SeedVR2_VideoUpscaler#39]
Hi there,

First of all, thank you for this incredible project! I've been using it to upscale several videos with great success, and the performance on a single GPU is fantastic and highly efficient.

I've run into an issue, however, when attempting to leverage multiple GPUs for video processing.

### System Environment
*   **GPU:** 4x NVIDIA H100 80GB (SXM)
*   **Environment:** The `CUDA_VISIBLE_DEVICES` environment variable is **not** set in my terminal.

#### 1. Single GPU Inference (Works Perfectly)
When I run the following command, the process starts correctly on the specified GPU (e.g., GPU 3) and completes successfully. This works as expected for any single GPU index.

```bash
python inference_cli.py --video_path "MAIN.mp4" --batch_size 50 --load_cap 1000 --output "./outputs/test_upscale.mp4" --cuda_device 3
```

#### 2. Multi-GPU Inference (Fails)
When I try to specify multiple GPUs, like so:

```bash
python inference_cli.py --video_path "MAIN.mp4" --batch_size 50 --load_cap 1000 --output "./outputs/test_upscale.mp4" --cuda_device 2,3
```

### Observed Behavior
I monitor the system using `nvtop` and observe the following:
1.  Instead of using GPUs 2 and 3, two processes are spawned on **GPU 0**.
2.  The VRAM on GPU 0 increases rapidly.
3.  The program crashes due to an Out-Of-Memory (OOM) error.

### Expected Behavior
I would expect the process to be distributed across the specified GPUs (e.g., one process on GPU 2 and another on GPU 3), sharing the workload and memory usage to avoid an OOM error.

### My Question
I'm not quite sure why this is happening. It seems as though the application is attempting to load resources for both device instances onto a single physical GPU.

Could you please provide some guidance on this?  Is there another configuration I might be missing?

Thank you again for your time and for this wonderful project

**Comment by nkkbr** [comment]
The issue has been resolved.

After commenting out the torch.cuda.init() line, the program was able to run properly across all four GPUs.
